fail github action if any of the tests failed

diff --git a/.github/workflows/deploy-playground-and-test.yml b/.github/workflows/deploy-playground-and-test.yml
--- a/.github/workflows/deploy-playground-and-test.yml
+++ b/.github/workflows/deploy-playground-and-test.yml
@@ -172,7 +172,12 @@ jobs:
           cd packages/tests-e2e
           BRANCH_NAME=$(echo $BRANCH_NAME_RAW | tr '/_' '-')
           export PLAYWRIGHT_TEST_URL="https://$BRANCH_NAME.react.playground.corbado.io"
-          PLAYWRIGHT_TEST_URL=$PLAYWRIGHT_TEST_URL npx playwright test --config=playwright.config.complete.ts
+          set +e
+          npx playwright test --config=playwright.config.complete.ts
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "COMPLETE_REACT_FAILED=true" >> $GITHUB_ENV
+          fi
         env:
           PLAYWRIGHT_NUM_CORES: 4
           PLAYWRIGHT_JWT_TOKEN: ${{ secrets.PLAYWRIGHT_JWT_TOKEN }}
@@ -215,7 +220,12 @@ jobs:
           cd packages/tests-e2e
           BRANCH_NAME=$(echo $BRANCH_NAME_RAW | tr '/_' '-')
           export PLAYWRIGHT_TEST_URL="https://$BRANCH_NAME.connect-next.playground.corbado.io"
-          PLAYWRIGHT_TEST_URL=$PLAYWRIGHT_TEST_URL npx playwright test --config=playwright.config.connect.ts
+          set +e
+          npx playwright test --config=playwright.config.complete.ts
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "CONNECT_REACT_FAILED=true" >> $GITHUB_ENV
+          fi
         env:
           PLAYWRIGHT_NUM_CORES: 4
           BACKEND_API_BASIC_AUTH: ${{ secrets.BACKEND_API_BASIC_AUTH }}
@@ -250,3 +260,26 @@ jobs:
           TIMESTAMP=$(date +%s000)
           LOG_EVENT_JSON="[{\"timestamp\":$TIMESTAMP,\"message\":\"$SUMMARY\"}]"
           aws logs put-log-events --log-group-name "test-results-board" --log-stream-name "$LOG_STREAM_NAME" --log-events "$LOG_EVENT_JSON"
+
+      - name: Aggregate results
+        run: |
+          FAILED_STEPS=""
+          if [ "${COMPLETE_REACT_FAILED}" = "true" ]; then
+            FAILED_STEPS="${FAILED_STEPS} Complete-React"
+          fi
+          if [ "${COMPLETE_WEBJS_FAILED}" = "true" ]; then
+            FAILED_STEPS="${FAILED_STEPS} Complete-WebJs"
+          fi
+          if [ "${COMPLETE_WEBJSSCRIPT_FAILED}" = "true" ]; then
+            FAILED_STEPS="${FAILED_STEPS} Complete-WebJsScript"
+          fi
+          if [ "${CONNECT_REACT_FAILED}" = "true" ]; then
+            FAILED_STEPS="${FAILED_STEPS} Connect-React"
+          fi
+
+          if [ -n "$FAILED_STEPS" ]; then
+            echo "The following test steps have failed: $FAILED_STEPS"
+            exit 1
+          else
+            echo "All tests passed."
+          fi
